name: youtube_player_webview
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 1.0.0+1
author:
repository: https://github.com/ravindrabarthwal/youtube_player_webview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

flutter:
  uses-material-design: true

  assets:
    - assets/speed.webp

