name: youtube_player_webview
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 1.0.0+1
author:
repository: https://github.com/ravindrabarthwal/youtube_player_webview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  #webview_flutter: ^1.0.1
  webview_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/speed.webp

